### ISSUE TITLE
ssl Solution?

### ISSUE THREAD

**Issue by nielsnuebel** [renekreijveld/macOS-Local-Development-Setup#12]
Do you have anything ready?

**Comment by renekreijveld** [comment]
If you mean to be able to test SSL locally, the answer is NO unfortunately.
If you need to test SSL locally I suggest to have a look at Devilbox: http://devilbox.org/

**Comment by nielsnuebel** [comment]
https://gist.github.com/jonathantneal/774e4b0b3d4d739cbc53 i tried this without success :(

**Comment by renekreijveld** [comment]
That might because what you found is based on the standard Apache of macOS. We use Homebrew-based Apache setup.
Found a possible solution: https://getgrav.org/blog/macos-mojave-apache-ssl
